In [1]:
import numpy as np

In [2]:
mylist = [1, 2, 3]

In [3]:
print(mylist)
type(mylist)

[1, 2, 3]


list

In [6]:
np.array(mylist)

array([1, 2, 3])

In [9]:
my_matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [10]:
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [11]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.arange(0, 101, 2)

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [20]:
np.zeros(5)
np.zeros((2, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [21]:
np.ones(5)
np.ones((2, 6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [24]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [26]:
np.linspace(0, 10, 13)

array([ 0.        ,  0.83333333,  1.66666667,  2.5       ,  3.33333333,
        4.16666667,  5.        ,  5.83333333,  6.66666667,  7.5       ,
        8.33333333,  9.16666667, 10.        ])

In [27]:
np.linspace(0, 4, 5)

array([0., 1., 2., 3., 4.])

In [30]:
len(np.linspace(0, 10, 5))


5

In [31]:
len(np.arange(0, 101, 2))

51

In [32]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [36]:
np.random.rand(2, 5)

array([[0.48319642, 0.48318003, 0.45300926, 0.10249133, 0.25586169],
       [0.63359014, 0.15378063, 0.72709917, 0.56506906, 0.95419523]])

In [37]:
np.random.randn(2, 5)

array([[-0.38730466,  1.75819642, -0.36429571,  0.28563392,  1.6434078 ],
       [-0.24372013, -0.66359157,  1.20270565, -0.15081538, -0.91026253]])

In [41]:
np.random.randint(1, 10, 3)

array([9, 2, 6])

In [43]:
np.random.randint(1, 10, (2, 5))

array([[3, 1, 4, 2, 9],
       [9, 1, 7, 9, 4]])

In [44]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

### Indexing and Selection ###

In [2]:
arr = np.arange(0, 10)

In [3]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
arr[2]

2

In [5]:
arr[1:5]

array([1, 2, 3, 4])

In [7]:
arr[5:]

array([5, 6, 7, 8, 9])

In [8]:
arr[-1]

9

In [11]:
arr[-1:0]

array([], dtype=int32)

In [12]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
arr[0:3] = 69

In [14]:
arr

array([69, 69, 69,  3,  4,  5,  6,  7,  8,  9])

In [15]:
arr_2d = np.array([[5, 10 ,15], [20, 25, 30], [35, 40, 45]])

In [16]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [17]:
arr_2d[0]

array([ 5, 10, 15])

In [18]:
arr_2d[-1]

array([35, 40, 45])

In [19]:
arr_2d[-1, 2]

45

In [21]:
dice_rolls = np.array([3, 1, 5, 2, 5, 1, 1, 5, 1, 4, 2, 1, 4, 5, 3, 4, 5, 2, 4, 2, 6, 6, 3, 6, 2, 3, 5, 6, 5])

total_rolls_over_two = dice_rolls[dice_rolls>2]

In [22]:
total_rolls_over_two

array([3, 5, 5, 5, 4, 4, 5, 3, 4, 5, 4, 6, 6, 3, 6, 3, 5, 6, 5])

In [23]:
total_rolls_over_two.shape

(19,)

In [3]:
arr = np.arange(0,10)

In [4]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
arr * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [6]:
arr / 2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [7]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [10]:
np.power(arr, 2)

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)